"""Script that merges multiple MLflow artifacts containing CAM masks generated by Adam Džadoň.

The generation details can be found in the Prostate Cancer repository.

Assumes the following structure of input data:
1. Exploratory Metadataset (`exploration/save_metadataset.py`):
<DATASET_NAME>/
    slides_metadata.csv (columns "slide_path" (str), "is_carcinoma" (bool), and "has_annotation" (bool))

The output is logged to MLflow as:
<MLFLOW_ARTIFACT_PATH>/
    <SLIDE_NAME>.tiff (CAM masks)
`missing_cam_masks.csv` (columns "slide_path" (str), "is_carcinoma" (bool), and "has_annotation" (bool))
"""

from pathlib import Path
from tempfile import TemporaryDirectory

import hydra
import pandas as pd
from mlflow.artifacts import download_artifacts, list_artifacts
from omegaconf import DictConfig
from rationai.mlkit import autolog, with_cli_args
from rationai.mlkit.lightning.loggers import MLFlowLogger


@with_cli_args(["+preprocessing=cam_masks"])
@hydra.main(config_path="../configs", config_name="preprocessing", version_base=None)
@autolog
def main(config: DictConfig, logger: MLFlowLogger) -> None:
    train_slides = pd.read_csv(download_artifacts(config.train_metadata_uri))
    test_slides = pd.read_csv(download_artifacts(config.test_metadata_uri))
    slides = pd.concat([train_slides, test_slides])

    with TemporaryDirectory() as output_dir:
        cam_masks: set[str] = set()
        for uri in config.uris:
            for slide_file in list_artifacts(uri):
                file = Path(slide_file.path)
                download_artifacts(f"{uri}/{file.name}", dst_path=output_dir)
                cam_masks.add(file.stem)

        logger.log_artifacts(
            local_dir=output_dir, artifact_path=config.mlflow_artifact_path
        )
        missing_mask = ~slides["slide_path"].map(lambda x: Path(x).stem).isin(cam_masks)
        missing_cams_df = slides[missing_mask][
            ["slide_path", "is_carcinoma", "has_annotation"]
        ]
        csv_path = Path(output_dir, "missing_cam_masks.csv")
        missing_cams_df.to_csv(csv_path, index=False)
        logger.log_artifact(local_path=str(csv_path))

        if len(missing_cams_df) > 0:
            print(
                f"[INFO] {len(missing_cams_df)} slides have no CAMs: \n{missing_cams_df}"
            )


if __name__ == "__main__":
    main()
