# @package _global_

defaults:
  - /data/sources/panda
  - _self_

mask_tile_width: ${dataset.mask_tile_width}
mask_tile_height: ${dataset.mask_tile_height}
max_concurrent: 12
metadata_uri: ${dataset.mlflow_uris.exploration}
annotations_dir: ${dataset.paths.masks.annotation}
mlflow_artifact_path: annotation_masks

metadata:
  run_name: "🖍️ Annotation Masks: ${dataset.name}"
  hyperparams:
    mask_tile_width: ${mask_tile_width}
    mask_tile_height: ${mask_tile_height}
