# @package _global_

defaults:
  - /data/sources/panda
  - _self_

split_uri: ???
metadata_uri: ${dataset.mlflow_uris.exploration}
nuclei_path: ${dataset.paths.nuclei.standardized}

metadata:
  run_name: "📁 Metadataset Mapping: ${dataset.name}"
