# @package _global_

noise_removal_radius: ???
min_pre_dilation_area: ???
dilation_disk_size: ???
max_hole_size: ???
min_final_object_size: ???
cleanup_scale: ???
patch_size: ???

max_concurrent: 6 # TODO
metadata_uri: ${dataset.mlflow_uris.exploration}
raw_masks_uri: ${dataset.mlflow_uris.masks.amacr.raw}
eroded_tissue_masks_uri: ${dataset.mlflow_uris.masks.tissue.eroded}
mlflow_artifact_path: amacr_masks_refined

metadata:
  run_name: "🎭 AMACR Masks, Refined: ${dataset.name}"
  hyperparams:
    noise_removal_radius: ${noise_removal_radius}
    min_pre_dilation_area: ${min_pre_dilation_area}
    dilation_disk_size: ${dilation_disk_size}
    max_hole_size: ${max_hole_size}
    min_final_object_size: ${min_final_object_size}
    cleanup_scale: ${cleanup_scale}
    patch_size: ${patch_size}
