# @package _global_

mask_tile_width: ???
mask_tile_height: ???

mask_min_area: ???
holes_min_area: ???
holes_max_area: ???
tile_size: ???
shadow_ratio: ???
brown_ratio: ???
sat_threshold: ???

max_concurrent: 6 # TODO
metadata_uri: ${dataset.mlflow_uris.exploration}
tissue_masks_uri: ${dataset.mlflow_uris.masks.tissue.raw}
mlflow_artifact_path: amacr_mask_raw

metadata:
  run_name: "🎭 AMACR Masks: ${dataset.name}"
  hyperparams:
    mask_tile_width: ${mask_tile_width}
    mask_tile_height: ${mask_tile_height}
    mask_min_area: ${mask_min_area}
    holes_min_area: ${holes_min_area}
    holes_max_area: ${holes_max_area}
    tile_size: ${tile_size}
    shadow_ratio: ${shadow_ratio}
    brown_ratio: ${brown_ratio}
    sat_threshold: ${sat_threshold}
