# @package _global_

annot_masks_uri: ???
max_concurrent: 6
overlap_threshold: ???
nuclei_path: ???
train_metadata_uri: ???
test_metadata_uri: ???
mlflow_artifact_path: annotation_labels

metadata:
  run_name: "🏷️ Nuclei Annotation-based Labeling: ${dataset.name}"
  hyperparams:
    overlap_threshold: ${overlap_threshold}
