# @package _global_

defaults:
  - segmentation
  - _self_

nuclei_path: ${output_path}
labels_uri: mlflow-artifacts:/97/13509217e14a4e42af5bba5c60f95674/artifacts/nuclei_labels
cam_masks_uri: mlflow-artifacts:/97/3035fa39faf44ef4ad12001e882f9868/artifacts/cam_masks
bipolar_zero_offset: 127.0
overlap_threshold: 0.5
positivity_threshold: 0.3 # determined by pathologist
mlflow_artifact_path: cam_label_indicators

metadata:
  run_name: CAM Label Indicator Masks
  hyperparams:
    overlap_threshold: ${overlap_threshold}
    positivity_threshold: ${positivity_threshold}
