# @package _global_

defaults:
  - /data/datasets/prostate_cancer
  - _self_

cam_masks_uri: ${dataset.mlflow_uris.masks.cam}
missing_cam_masks_uri: ${dataset.mlflow_uris.masks.missing.cam}
max_concurrent: 6
overlap_threshold: ???
bipolar_zero_offset: 127.5
positive_threshold: ???
negative_threshold: ???
train_metadata_uri: ${dataset.mlflow_uris.exploration.train}
test_metadata_uri: ${dataset.mlflow_uris.exploration.test}
nuclei_path: ${dataset.paths.nuclei_seg}
mlflow_artifact_path: cam_labels

metadata:
  run_name: "🔍 CAM-based Labeling: ${dataset.name}"
  hyperparams:
    overlap_threshold: ${overlap_threshold}
    positive_threshold: ${positive_threshold}
    negative_threshold: ${negative_threshold}
