# @package _global_

cam_masks_uri: ${dataset.mlflow_uris.masks.cam}
missing_cam_masks_uri: ${dataset.mlflow_uris.masks.missing.cam}
max_concurrent: 6
overlap_threshold: ???
bipolar_zero_offset: 127.5
positive_threshold: ???
negative_threshold: ???
metadata_uris: 
  - ${dataset.mlflow_uris.metadata.train}
  - ${dataset.mlflow_uris.metadata.test}
nuclei_path: ${dataset.paths.nuclei_seg}
threshold_type: ???
output_path: ${dataset.paths.supervision.cam.${threshold_type}}

metadata:
  run_name: "🔍 CAM-based Labeling: ${dataset.name}"
  hyperparams:
    overlap_threshold: ${overlap_threshold}
    positive_threshold: ${positive_threshold}
    negative_threshold: ${negative_threshold}
    threshold_type: ${threshold_type}
