# @package _global_

defaults:
  - segmentation
  - _self_

labels_uri: mlflow-artifacts:/97/6fbf134f753c4d33870fa6a91ce52d69/artifacts/annotation_labels
cam_masks_uri: mlflow-artifacts:/97/5ce428634d6c4ec095c9259bdef87eca/artifacts/cam_masks
max_concurrent: 100
bipolar_zero_offset: 127.0
overlap_threshold: 0.5
positivity_threshold: 0.3 # determined by pathologist
nuclei_path: ${output_path}
mlflow_artifact_path: cam_label_indicators

metadata:
  run_name: CAM Label Indicators
  hyperparams:
    overlap_threshold: ${overlap_threshold}
    positivity_threshold: ${positivity_threshold}
