# @package _global_

test_size: ???
stratify_column: ???
restriction: # subset of the data to split for provider-specific splits
  provider_column: ???
  provider_value: ???
metadata_uri: ${dataset.mlflow_uris.exploration}
mlflow_artifact_path: split

metadata:
  run_name: "Train-Test Split: ${dataset.name}"
  hyperparams:
    test_size: ${test_size}
    stratify_column: ${stratify_column}
    provider_column: ${restriction.provider_column}
    provider_value: ${restriction.provider_value}
