# @package _global_

test_size: ???
stratify_column: ???
restriction: # subset of the data to split, e.g. specific data provider
  subset_column: ???
  target_value: ???
metadata_uri: ${dataset.mlflow_uris.exploration}
mlflow_artifact_path: panda_split

metadata:
  run_name: "Train-Test Split: ${dataset.name}"
  hyperparams:
    test_size: ${test_size}
    stratify_column: ${stratify_column}
    subset_column: ${restriction.subset_column}
    target_value: ${restriction.target_value}
