# @package _global_

train_metadata_uri: ${dataset.mlflow_uris.metadata.train}
test_metadata_uri: ${dataset.mlflow_uris.metadata.test}
train_data_path: ${dataset.paths.wsi_data.train}
test_data_path: ${dataset.paths.wsi_data.test}
efd_order: 20 # maximum number of harmonics that can be used as features later on
max_concurrent: 8
output_path: ${project_path}/nuclei_efd

metadata:
  run_name: "Nuclei EFD Features: ${dataset.name}"
  hyperparams:
    efd_order: ${efd_order}
    output_path: ${output_path}
