# @package _global_

defaults:
  - base
  - _self_

uris:
  - mlflow-artifacts:/72/2efe349e0c6f402898e3d94cc66f820f/artifacts/Archive Tumor Cases
  - mlflow-artifacts:/72/06e8d6d89a014081b94e02dbdf80c1ae/artifacts/Prospective Tumor Cases
  - mlflow-artifacts:/72/efa8c70cdb62408a87e278e42fbc49e1/artifacts/Prospective Test Cases
artifact_path: cam_masks

metadata:
  run_name: CAM Masks for Positive Slides
  description: |
    This run merges multiple MLflow artifact datasets containing CAM masks:
    - [🎭 Explanainability Masks - Archive Tumor Cases](https://mlflow.rationai.cloud.trusted.e-infra.cz/#/experiments/72/runs/2efe349e0c6f402898e3d94cc66f820f)
    - [🎭 Explanainability Masks - Prospective Tumor Cases](https://mlflow.rationai.cloud.trusted.e-infra.cz/#/experiments/72/runs/06e8d6d89a014081b94e02dbdf80c1ae)
    - [🎭 Explanainability Masks - Prospective Test Cases](https://mlflow.rationai.cloud.trusted.e-infra.cz/#/experiments/72/runs/efa8c70cdb62408a87e278e42fbc49e1)

    Only positive slides are kept.

    CAM mask generation details:
    **Model**: [VGG-16 Prostate Classifier](https://mlflow.rationai.cloud.trusted.e-infra.cz/#/experiments/4/runs/c38a483305574912a2b3f15bc64a2284)
    **Data**: 
        - [Tiling: Archive tumor cases](https://mlflow.rationai.cloud.trusted.e-infra.cz/#/experiments/4/runs/a51f32dae178463b813103615670c515)
        - [Tiling: Tumor cases](https://mlflow.rationai.cloud.trusted.e-infra.cz/#/experiments/4/runs/dd8e6c4b8ec44bbdb9f0975acb278673)
        - [Tiling: Test cases](https://mlflow.rationai.cloud.trusted.e-infra.cz/#/experiments/4/runs/42a6acd9b91942b4838646b6e9a2c158)

    Some slides do not have a corresponding CAM mask — these are logged in `missing_cam_slides.csv`.
  hyperparams:
    level: 1
