# @package _global_

defaults:
  - segmentation
  - _self_

missing_annotations_uri: mlflow-artifacts:/97/dab2028a50e7431ba0e93f617b5242b6/artifacts/missing_annotations.csv
missing_cams_uri: mlflow-artifacts:/97/5ce428634d6c4ec095c9259bdef87eca/artifacts/missing_cam_masks.csv
nuclei_seg_path: ${output_path}

metadata:
  run_name: Metadataset Mapping
