# @package _global_

exclude_slides_uris: ???
train_metadata_uri: ???
test_metadata_uri: ???
train_data_path: ???
test_data_path: ???
nuclei_seg_path: ???

metadata:
  run_name: "📁 Metadataset Mapping: ${dataset.name}"
