# @package _global_

train_metadata_uri: ${dataset.mlflow_uris.exploration.train}
test_metadata_uri: ${dataset.mlflow_uris.exploration.test}
exclude_slides_uris: ???
nuclei_seg_path: ???

metadata:
  run_name: "📁 Metadataset Mapping: ${dataset.name}"
