# @package _global_

defaults:
  - segmentation
  - _self_

nuclei_path: ${output_path}
annot_masks_uri: mlflow-artifacts:/97/0f1925cc96554daaa7b9d4926ab169cf/artifacts/annotation_masks
overlap_threshold: 1.0
mlflow_artifact_path: nuclei_labels

metadata:
  run_name: Nuclei Labeling
