# @package _global_

defaults:
  - segmentation
  - _self_

annot_masks_uri: mlflow-artifacts:/97/dab2028a50e7431ba0e93f617b5242b6/artifacts/annotation_masks
max_concurrent: 100
overlap_threshold: 1.0
nuclei_path: ${output_path}
mlflow_artifact_path: annotation_labels

metadata:
  run_name: Nuclei Annotation Labeling
  hyperparams:
    overlap_threshold: ${overlap_threshold}
