# @package _global_

metadata_uri: ${dataset.mlflow_uris.exploration.train}
nuclei_source_path: ${dataset.paths.nuclei_seg_radial}
max_concurrent: 10
output_path: ${dataset.paths.nuclei_seg}

metadata:
  run_name: "Nuclei Data Standardization"
