# @package _global_

metadata_uri: ${dataset.mlflow_uris.exploration}
level: 3
max_concurrent: 20
mask_tile_width: 512
mask_tile_height: 512

metadata:
  run_name: "Tissue Masks: ${dataset.name}"
  hyperparams:
    level: ${level}
    mask_tile_width: ${mask_tile_width}
    mask_tile_height: ${mask_tile_height}