defaults:
  - _self_
  - hydra: default
  - mlflow: default
  - reporter: ???

user: ???

reporter:
  _target_: report.reporter.ReportAssembler
  save: ???
  background: ???
  title: ???
  mask_retrievers: []
  metrics_run_ids: []
  template_asset_path: report_template.html
