# @package _global_

defaults:
  - /data/sources/icaird_cervix
  - _self_

mask_tile_width: ${dataset.mask_tile_width}
mask_tile_height: ${dataset.mask_tile_height}
visualization_mode: ???
level: 2  # 1 µm/px
max_concurrent: 1
heatmap_labels_dir: null
label_column: null
cam_labels_dir: null
predictions_uri: null
pred_thr: null
metadata_uris: ???  # metadata parquet(s) with `slide_path` and `slide_nuclei_path`
nuclei_path: ${dataset.paths.nuclei_seg}/cervix
mlflow_artifact_path: nuclei_masks

metadata:
  run_name: ???
  hyperparams:
    mask_tile_width: ${mask_tile_width}
    mask_tile_height: ${mask_tile_height}
    level: ${level}
