# @package _global_

defaults:
  - /data/sources/panda
  - _self_

mask_tile_width: ${dataset.mask_tile_width}
mask_tile_height: ${dataset.mask_tile_height}
visualization_mode: ???
max_concurrent: 1
heatmap_labels_uri: ${dataset.providers.radboud.supervision.annotation}
label_column: null
cam_labels_uri: null
predictions_uri: null
pred_thr: null
metadata_uris:
  #- ${dataset.providers.radboud.metadata.train}
  - ${dataset.providers.radboud.metadata.test}
nuclei_path: ${dataset.paths.nuclei.standardized}
mlflow_artifact_path: nuclei_masks

metadata:
  run_name: ???
  hyperparams:
    mask_tile_width: ${mask_tile_width}
    mask_tile_height: ${mask_tile_height}