# @package _global_

pooled_predictions_uri: ???
metadata_uri: ???
slides_uri: ???
level: 2

mlflow_artifact_path: tile_heatmaps
mlflow_run_id: null
mlflow_parent_run_id: null

metadata:
  run_name: Tile-level Heatmaps
