# @package _global_

metadata_uri: ???
predictions_uri: ???
label_column: ???
threshold: ???

mlflow_artifact_path: slide_tile_metrics.json
mlflow_run_id: null
mlflow_parent_run_id: null

checkpoint: ???

metadata:
  run_name: TL Test (MMCI) Evaluation
  hyperparams:
    threshold: ${threshold}
