# @package _global_

nuclei_predictions_uri: ???
metadata_uri: ???
pooling_mode: ???
pooling_k: null

mlflow_artifact_path: tile_predictions
mlflow_run_id: null
mlflow_parent_run_id: null

data:
  dataset:
    uris: ${dataset.mlflow_uris.tiles.test}
    tile_size: ???
    margin: ???
    efd_order: ???
    embedding_mode: ???
    thresholds: ???

checkpoint: ???

metadata:
  run_name: "Evaluation: Nuclei to Tile Pooling"
  hyperparams:
    pooling_mode: ${pooling_mode}
    pooling_k: ${oc.select:pooling_k,null}
