"""Script for creating a visualization of the nuclei segmentation results.

Assumes the following structure of the segmented nuclei (generated by `nuclei_segmentation.py`):
<NUCLEI_SEGMENTATION_PATH>/
    <DATASET_NAME>/
        slide_id=<SLIDE_NAME>/
            *.parquet (segmented nuclei with keys "id", "polygon", and "centroid")

The resulting .tiff masks are stored as artifacts in MLflow.
"""

from pathlib import Path
from tempfile import TemporaryDirectory

import hydra
import pandas as pd
import pyvips
import ray
from einops import rearrange
from mlflow.artifacts import download_artifacts
from omegaconf import DictConfig
from PIL import Image, ImageDraw
from rationai.masks import (
    process_items,
    write_big_tiff,
)
from rationai.mlkit import autolog
from rationai.mlkit.lightning.loggers import MLFlowLogger
from ratiopath.openslide import OpenSlide


@ray.remote(memory=60 * 1024**3)
def process_slide(
    slide_path: Path,
    mpp: float,
    mask_tile_width: int,
    mask_tile_height: int,
    nuclei_path: Path,
    output_path: Path,
) -> None:
    with OpenSlide(slide_path) as slide:
        level = slide.closest_level(mpp)
        mpp_x, mpp_y = slide.slide_resolution(level)
        mask_size = slide.level_dimensions[level]

    mask = Image.new("L", size=mask_size)
    canvas = ImageDraw.Draw(mask)

    nuclei = pd.read_parquet(
        nuclei_path
        / slide_path.parents[0].name  # dataset_name
        / f"slide_id={slide_path.stem}"
    )
    for _, nucleus in nuclei.iterrows():
        polygon = rearrange(nucleus["polygon"], "(n c) -> n c", c=2)
        canvas.polygon(xy=polygon, outline=255)

    write_big_tiff(
        pyvips.Image.new_from_array(mask),
        path=output_path / slide_path.with_suffix(".tiff").name,
        mpp_x=mpp_x,
        mpp_y=mpp_y,
        tile_width=mask_tile_width,
        tile_height=mask_tile_height,
    )


@hydra.main(
    config_path="../configs",
    config_name="visualization/polygon2raster",
    version_base=None,
)
@autolog
def main(config: DictConfig, logger: MLFlowLogger) -> None:
    train_slides = pd.read_csv(download_artifacts(config.train_metadata_uri))
    test_slides = pd.read_csv(download_artifacts(config.test_metadata_uri))
    slides = pd.concat([train_slides, test_slides])

    with TemporaryDirectory() as output_dir:
        process_items(
            slides["slide_path"].map(Path),
            process_item=process_slide,
            fn_kwargs={
                "mpp": config.mpp,
                "mask_tile_width": config.mask_tile_width,
                "mask_tile_height": config.mask_tile_height,
                "nuclei_path": Path(config.nuclei_path),
                "output_path": Path(output_dir),
            },
            max_concurrent=config.max_concurrent,
        )
        logger.log_artifacts(
            local_dir=output_dir, artifact_path=config.mlflow_artifact_path
        )


if __name__ == "__main__":
    ray.init()
    main()
    ray.shutdown()
