"""Script for creating a visualization of the nuclei segmentation results and their labels.

Assumes the following structure of the segmented nuclei generated by `nuclei_segmentation.py`:
<NUCLEI_SEGMENTATION_PATH>/
    <DATASET_NAME>/
        slide_id=<SLIDE_NAME>/
            *.parquet (segmented nuclei with keys "polygon", "centroid", and "id")

and that nuclei labels are stored as partitioned .parquet files generated by `label_nuclei.py`:
<MLFLOW_ARTIFACT_PATH>/
    <DATASET_NAME>/
        <SLIDE_NAME>.parquet (a table with columns "slide_id", "id", and "label")

Optionally, the visualization can be restricted to CAM-based refinement of positive slides generated by
`compute_cam_indicators.py` with the following structure:
<MLFLOW_ARTIFACT_PATH>/
    <DATASET_NAME>/
        <SLIDE_NAME>.parquet (a table with columns "slide_id", "id", and "label_indicator")

The resulting .tiff masks are stored as artifacts in MLflow:
<MLFLOW_ARTIFACT_PATH>/
    <SLIDE_NAME>.tiff (rasterized nuclei filled according to their labels)
"""

from pathlib import Path
from tempfile import TemporaryDirectory

import hydra
import numpy as np
import pandas as pd
import pyvips
import ray
from einops import rearrange
from mlflow.artifacts import download_artifacts
from omegaconf import DictConfig
from PIL import Image, ImageDraw
from rationai.masks import process_items, write_big_tiff
from rationai.mlkit import autolog
from rationai.mlkit.lightning.loggers import MLFlowLogger
from ratiopath.openslide import OpenSlide


def get_labels(labels_path: Path, cam_path: Path | None) -> pd.DataFrame:
    labels_df = pd.read_parquet(labels_path)

    if cam_path is None or not cam_path.exists():
        print(f"[WARNING] Missing CAM mask for slide {labels_path.name}.")
        return labels_df[["id", "label"]]

    merged = labels_df.merge(pd.read_parquet(cam_path), on="id", how="inner")
    merged["label"] = (merged["label"] * merged["label_indicator"]).astype("uint8")
    return merged[["id", "label"]]


@ray.remote(memory=15 * 1024**3)
def process_slide(
    slide_path: Path,
    mpp: float,
    mask_tile_width: int,
    mask_tile_height: int,
    nuclei_dir: Path,
    output_dir: Path,
    labels_dir: Path,
    cam_dir: Path | None,
) -> None:
    with OpenSlide(slide_path) as slide:
        level = slide.closest_level(mpp)
        mpp_x, mpp_y = slide.slide_resolution(level)
        mask_size = slide.level_dimensions[level]

    mask = Image.new("L", size=mask_size)
    canvas = ImageDraw.Draw(mask)

    dataset_name = slide_path.parents[0].name
    nuclei = pd.read_parquet(nuclei_dir / dataset_name / f"slide_id={slide_path.stem}")

    labels_df = get_labels(
        labels_path=labels_dir / dataset_name / f"{slide_path.stem}.parquet",
        cam_path=None
        if cam_dir is None
        else cam_dir / dataset_name / f"{slide_path.stem}.parquet",
    )
    nuclei_labeled = nuclei.merge(labels_df, on="id", how="inner")

    for row in nuclei_labeled.itertuples(index=False):
        polygon = rearrange(row.polygon, "(n c) -> n c", c=2)
        canvas.polygon(xy=polygon, outline=255, fill=int(row.label) * 255)

    write_big_tiff(
        image=pyvips.Image.new_from_array(np.array(mask)),
        path=output_dir / slide_path.with_suffix(".tiff").name,
        mpp_x=mpp_x,
        mpp_y=mpp_y,
        tile_width=mask_tile_width,
        tile_height=mask_tile_height,
    )


@hydra.main(
    config_path="../configs",
    config_name="visualization/polygon2raster",
    version_base=None,
)
@autolog
def main(config: DictConfig, logger: MLFlowLogger) -> None:
    train_slides = pd.read_csv(download_artifacts(config.train_metadata_uri))
    test_slides = pd.read_csv(download_artifacts(config.test_metadata_uri))
    slides = pd.concat([train_slides, test_slides])

    with TemporaryDirectory() as output_dir:
        process_items(
            slides["slide_path"].map(Path),
            process_item=process_slide,
            fn_kwargs={
                "mpp": config.mpp,
                "mask_tile_width": config.mask_tile_width,
                "mask_tile_height": config.mask_tile_height,
                "nuclei_dir": Path(config.nuclei_path),
                "output_dir": Path(output_dir),
                "labels_dir": Path(download_artifacts(config.labels_uri)),
                "cam_dir": (
                    Path(download_artifacts(config.cam_indicators_uri))
                    if config.cam_indicators_uri is not None
                    else None
                ),
            },
            max_concurrent=config.max_concurrent,
        )
        logger.log_artifacts(
            local_dir=output_dir, artifact_path=config.mlflow_artifact_path
        )


if __name__ == "__main__":
    ray.init()
    main()
    ray.shutdown()
