"""Script for creating a visualisation of the nuclei segmentation results and their labels.

Assumes the following structure of the segmented nuclei (generated by `nuclei_segmentation.py`:
<NUCLEI_SEGMENTATION_BASE_PATH>/
    dataset_name=<DATASET_NAME>/
        nuclei/
            slide_id=<SLIDE_NAME>/
                *.parquet (segmented nuclei with keys "slide_id", "polygon", "centroid" and "nucleus_id")

and that nuclei labels stored as partitioned .parquet files (generated by `label_nuclei.py`):
- nuclei_labels/
    dataset_name=<DATASET_NAME>/
        slide_id=<SLIDE_NAME>/
            *.parquet (file with columns "slide_id", "nucleus_id", and "label")

Optionally, the visualisation can be restricted to CAM refinement masks of positive slides,
which represent CAM-based relabeling of nuclei produced by `relabel_nuclei_with_cam.py`:
- cam_label_indicators/
    dataset_name=<DATASET_NAME>/
        slide_id=<SLIDE_NAME>/
            *.parquet (file with columns "slide_id", "nucleus_id" and "cam_label_indicator")

The resulting .tiff masks are stored as artifacts in MLflow under `nuclei_masks/`.
"""

from pathlib import Path
from tempfile import TemporaryDirectory

import hydra
import pandas as pd
import pyvips
import ray
import torch
from mlflow.artifacts import download_artifacts
from omegaconf import DictConfig
from openslide import OpenSlide
from preprocessing.slide_helpers import get_ground_truth, get_slide_paths
from pyvips import Image
from rationai.masks import process_items, slide_resolution
from rationai.mlkit import autolog
from rationai.mlkit.lightning.loggers import MLFlowLogger

from visualization.nuclei_mask import NucleiMask


MASK_TILE_WIDTH = 256
MASK_TILE_HEIGHT = 256


def get_mask(
    slide: OpenSlide,
    nuclei_path: Path,
    level: int,
    nuclei_labels_path: Path,
    cam_indicator_path: Path | None,
) -> tuple[Image, float, float]:
    base_mpp_x, base_mpp_y = slide_resolution(slide, level=0)
    mask_mpp_x, mask_mpp_y = slide_resolution(slide, level=level)
    mask_size = slide.level_dimensions[level]

    labels_df = (
        pd.read_parquet(nuclei_labels_path)
        .sort_values("nucleus_id")
        .reset_index(drop=True)
    )
    labels = torch.tensor(labels_df["label"].values, dtype=torch.uint8)
    if cam_indicator_path is not None:
        cam_label_indicators_df = (
            pd.read_parquet(cam_indicator_path)
            .sort_values("nucleus_id")
            .reset_index(drop=True)
        )
        cam_mask = torch.tensor(
            cam_label_indicators_df["cam_label_indicator"], dtype=torch.uint8
        )
        labels = labels * cam_mask

    mask = NucleiMask(
        base_mpp_x=base_mpp_x,
        base_mpp_y=base_mpp_y,
        mask_size=mask_size,
        mask_mpp_x=mask_mpp_x,
        mask_mpp_y=mask_mpp_y,
        nuclei_path=str(nuclei_path),
        labels=labels,
    )()
    return pyvips.Image.new_from_array(mask), mask_mpp_x, mask_mpp_y


def get_cam_indicator_path(
    slide_path: Path,
    use_cam: bool,
    dataset_name: str,
    cam_indicators_dir: Path | None,
) -> Path | None:
    if not use_cam or cam_indicators_dir is None:
        return None

    ground_truth = get_ground_truth(slide_path)
    if ground_truth != 1:
        return None

    slide_id = slide_path.stem
    cam_indicator_path = cam_indicators_dir / dataset_name / f"slide_id={slide_id}"
    if not cam_indicator_path.exists():
        print(f"[WARNING] Missing CAM mask — {cam_indicator_path.name} does not exist.")
        return None
    return cam_indicator_path


@ray.remote(memory=3 * 1024**3)
def process_slide(
    slide_path: Path,
    level: int,
    nuclei_seg_path: Path,
    output_path: Path,
    nuclei_labels_dir: Path,
    use_cam: bool,
    cam_indicators_dir: Path | None,
) -> None:
    slide_id = slide_path.stem
    dataset_name = slide_path.parents[0].name
    nuclei_path = (
        Path(nuclei_seg_path) / dataset_name / "nuclei" / f"slide_id={slide_id}"
    )
    cam_indicator_path = get_cam_indicator_path(
        slide_path, use_cam, dataset_name, cam_indicators_dir
    )
    nuclei_labels_path = nuclei_labels_dir / dataset_name / f"slide_id={slide_id}"

    with OpenSlide(slide_path) as slide:
        mask, mpp_x, mpp_y = get_mask(
            slide, nuclei_path, level, nuclei_labels_path, cam_indicator_path
        )

    mask_path = output_path / slide_path.with_suffix(".tiff").name

    xres = 1000 / mpp_x
    yres = 1000 / mpp_y

    mask.tiffsave(
        mask_path,
        bigtiff=True,
        compression=pyvips.enums.ForeignTiffCompression.DEFLATE,
        tile=True,
        tile_width=MASK_TILE_WIDTH,
        tile_height=MASK_TILE_HEIGHT,
        xres=xres,
        yres=yres,
        pyramid=True,
    )


def get_cam_indicators_dir(
    use_cam: bool, cam_indicators_uri: str | None
) -> Path | None:
    cam_indicators_dir = None
    if use_cam:
        assert cam_indicators_uri is not None, (
            "CAM masks URI must be set in the config."
        )
        cam_indicators_dir = Path(download_artifacts(cam_indicators_uri))
    return cam_indicators_dir


@hydra.main(
    config_path="../configs",
    config_name="visualization/polygon2raster",
    version_base=None,
)
@autolog
def main(config: DictConfig, logger: MLFlowLogger | None = None) -> None:
    assert logger is not None, "Need logger."
    train_slides_paths = get_slide_paths(Path(download_artifacts(config.metadata_uri)))
    test_slides_paths = get_slide_paths(
        Path(download_artifacts(config.test_metadata_uri))
    )
    use_cam: bool = config.use_cam
    cam_indicators_dir = get_cam_indicators_dir(use_cam, config.cam_indicators_uri)
    nuclei_labels_dir = Path(download_artifacts(config.nuclei_labels_uri))

    with TemporaryDirectory() as output_dir:
        process_items(
            train_slides_paths + test_slides_paths,
            process_item=process_slide,
            fn_kwargs={
                "level": config.level,
                "nuclei_seg_path": Path(config.nuclei_seg_path),
                "output_path": Path(output_dir),
                "nuclei_labels_dir": nuclei_labels_dir,
                "use_cam": use_cam,
                "cam_indicators_dir": cam_indicators_dir,
            },
            max_concurrent=config.max_concurrent,
        )
        logger.log_artifacts(local_dir=output_dir, artifact_path=config.artifact_path)

    logger.log_hyperparams(
        {
            "Level": config.level,
            "Mask Tile Width": MASK_TILE_WIDTH,
            "Mask Tile Height": MASK_TILE_HEIGHT,
        }
    )


if __name__ == "__main__":
    ray.init()
    main()
    ray.shutdown()
