# @package _global_

mlflow:
  tracking_uri: http://mlflow.rationai-mlflow:5000/

metadata_csv: /home/jovyan/nuclei-graph-transformer/data/beetle/slides_metadata.csv

reporter:
  title: BEETLE Dataset
  metrics_run_ids: []
  metrics_target_metrics: []
  template_asset_path: report_template.html

  save:
    _target_: report.save.MLFlowReportStorer
    artifact_path: report.html
    metadata:
      user: xrusnack
      experiment_name: Nuclei Graph — Transformer
      run_name: Report
      description: ""

  evaluation_runs: []

  background:
    _target_: report.masks.SlideRetriever
    paths:
      _target_: report.masks.csv_slide_retriever
      csv_path: ${metadata_csv}
      column: wsi_path
    layer_name: BEETLE WSI

  mask_retrievers:
    - _target_: report.masks.RunIDMlflowMaskRetriever
      run_id: 81d02429e65845029e7415986d91e485
      dir_name: annotation_masks/invasive_epithelium
      layer_name: "Invasive Epithelium"
      shader_conf:
        visible: True
        type: heatmap
        color: "#FFA500"

    - _target_: report.masks.RunIDMlflowMaskRetriever
      run_id: 81d02429e65845029e7415986d91e485
      dir_name: annotation_masks/non-invasive_epithelium
      layer_name: "Non-invasive Epithelium"
      shader_conf:
        visible: True
        type: heatmap
        color: "#00FF00"  # green

    - _target_: report.masks.RunIDMlflowMaskRetriever
      run_id: 81d02429e65845029e7415986d91e485
      dir_name: annotation_masks/necrosis
      layer_name: "Necrosis"
      shader_conf:
        visible: True
        type: heatmap
        color: "#FF0000"  # red

    - _target_: report.masks.RunIDMlflowMaskRetriever
      run_id: 81d02429e65845029e7415986d91e485
      dir_name: annotation_masks/other
      layer_name: "Other"
      shader_conf:
        visible: True
        type: heatmap
        color: "#0000FF"  # blue


metadata:
  run_name: Report — BEETLE dataset
  description: ""
