"""Generates a Forest Plot from MLflow CSV artifacts.

Fetches the CSV files generated by the postprocessing script, filters them
for the desired configurations, and plots the specified metrics with their
95% confidence intervals across independent subplots for proper scaling.
"""

import sys
from pathlib import Path
from tempfile import TemporaryDirectory

import hydra
import matplotlib
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
import pandas as pd
from mlflow.artifacts import download_artifacts
from omegaconf import DictConfig, OmegaConf
from rationai.mlkit import autolog, with_cli_args
from rationai.mlkit.lightning.loggers import MLFlowLogger

matplotlib.rcParams.update({
    'figure.max_open_warning': 0,
    'figure.dpi': 300,
    'savefig.dpi': 600,
    'savefig.bbox': 'tight'
})


def load_plot_data(inputs_config) -> pd.DataFrame:
    """Downloads artifacts from MLflow and extracts the target rows."""
    records = []
    
    for item in inputs_config:
        label = item.get("label")
        uri = item.get("uri")
        query = item.get("query")
        
        print(f"Fetching data for: {label}")
        try:
            local_path = download_artifacts(uri)
            df = pd.read_csv(local_path)
            
            if query:
                df = df.query(query)
                
            if df.empty:
                print(f"  -> WARNING: No rows matched query '{query}' in {uri}", file=sys.stderr)
                continue
                
            record = df.iloc[0].to_dict()
            record["Model"] = label
            records.append(record)
            
        except Exception as e:
            print(f"  -> ERROR fetching {uri}: {e}", file=sys.stderr)
            
    return pd.DataFrame(records)


def create_forest_plot(df: pd.DataFrame, metrics: list[str], output_path: Path):
    """Generates a grouped forest plot with independent axes and data columns."""
    present = [m for m in metrics if m in df.columns]
    if not present or df.empty:
        print("No valid metrics found to plot.", file=sys.stderr)
        return

    df = df.iloc[::-1].reset_index(drop=True)
    y_pos = np.arange(len(df))
    
    fig_height = max(5.0, len(df) * 0.9)
    
    fig, axes = plt.subplots(
        1, len(present), figsize=(6.5 * len(present) + 3, fig_height), sharey=True
    )
    if len(present) == 1:
        axes = [axes]
        
    colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']
    
    for i, (ax, metric) in enumerate(zip(axes, present)):
        val = df[metric].to_numpy(dtype=float)
        lo = df.get(f"{metric}_lo", pd.Series(val, index=df.index)).to_numpy(dtype=float)
        hi = df.get(f"{metric}_hi", pd.Series(val, index=df.index)).to_numpy(dtype=float)
        
        xerr_lo = np.where(np.isnan(lo), 0, val - lo)
        xerr_hi = np.where(np.isnan(hi), 0, hi - val)
        
        ax.errorbar(
            val, y_pos, xerr=[xerr_lo, xerr_hi], fmt='o',
            color=colors[i % len(colors)], ecolor=colors[i % len(colors)],
            capsize=5, markersize=8, linewidth=2
        )
        for j in range(len(val)):
            if not np.isnan(val[j]):
                label_text = f"{val[j]:.3f}\n[{lo[j]:.3f}, {hi[j]:.3f}]"
                ax.text(
                    1.15, y_pos[j],
                    label_text, 
                    transform=ax.get_yaxis_transform(), 
                    ha='center',    
                    va='center', 
                    fontsize=10,
                    color='#333333',
                    fontfamily='monospace'
                )
                
        ax.text(
            1.15, 1.02,            
            "Value\n[95% CI]", 
            transform=ax.transAxes,
            ha='center',           
            va='bottom', 
            fontsize=10,
            fontweight='bold',
            color='#333333'
        )
        
        ax.set_xlabel(f"{metric} (95% CI)", fontsize=12, fontweight='bold')
        ax.grid(axis='x', linestyle='--', alpha=0.7)
        ax.set_axisbelow(True)
        ax.spines[["top", "right"]].set_visible(False)
        
        min_x = np.nanmin(lo)
        max_x = np.nanmax(hi)
        pad = (max_x - min_x) * 0.15 if max_x > min_x else 0.05
        ax.set_xlim(min_x - pad, max_x + pad)
        
        ax.xaxis.set_major_locator(ticker.MaxNLocator(nbins=4))
        ax.xaxis.set_major_formatter(ticker.FormatStrFormatter('%.2f'))

    axes[0].set_yticks(y_pos)
    axes[0].set_yticklabels(df["Model"], fontsize=12)
    fig.suptitle("Performance by Modality", fontsize=15, fontweight='bold')
    
    fig.tight_layout()
    fig.subplots_adjust(wspace=0.55, right=0.88) 
    
    plt.savefig(output_path)
    plt.close(fig)
    print(f"Saved High-Res Forest Plot to {output_path}")


@with_cli_args(["+postprocessing=plots/forest"])
@hydra.main(config_path="../../configs", config_name="postprocessing", version_base=None)
@autolog
def main(config: DictConfig, logger: MLFlowLogger) -> None:
    if config.get("mlflow_tracking_uri"):
        import mlflow
        mlflow.set_tracking_uri(config.mlflow_tracking_uri)
        
    inputs = OmegaConf.to_object(config.get("inputs", []))
    metrics = OmegaConf.to_object(config.get("metrics", ["AUROC", "AUPRC"]))
    
    if not inputs:
        raise ValueError("No inputs provided. Please define 'inputs' in your Hydra config.")
        
    df = load_plot_data(inputs)
    
    if df.empty:
        print("No data extracted. Exiting.", file=sys.stderr)
        return

    with TemporaryDirectory() as output_dir:
        out_path = Path(output_dir) / "forest_plot.png"
        create_forest_plot(df, metrics, out_path)
        
        logger.log_artifacts(
            local_dir=str(output_dir), 
            artifact_path=config.get("mlflow_artifact_path", "plots")
        )

if __name__ == "__main__":
    main()