# @package _global_

defaults:
  - /preprocessing: segmentation
  - _self_

# Note: tile sizes need to be consistent across masks to display correctly in xOpat
mask_tile_width: 512
mask_tile_height: 512
max_concurrent: 1
nuclei_path: ${output_path}
mlflow_artifact_path: nuclei_masks

metadata:
  run_name: Nuclei Visualization
  hyperparams:
    mask_tile_width: ${mask_tile_width}
    mask_tile_height: ${mask_tile_height}
