# @package _global_

defaults:
  - /preprocessing: segmentation
  - _self_

visualization_mode_names:
  "1": Outline Polygons
  "2": Model Predictions
  "3": Annotation-based Labeling
  "4": CAM-based Pseudo Labeling

# Note: tile sizes need to be consistent across masks to display correctly in xOpat
mask_tile_width: 512
mask_tile_height: 512
predictions_uri: null # TODO
pred_thr: # threshold for determining positive nuclei
annot_labels_uri: mlflow-artifacts:/97/ff4a94b4f1c14c5ebc63d46f13a9e8de/artifacts/annotation_labels
cam_labels_uri: mlflow-artifacts:/97/205869b9ca3c4a9bbe6341035e0d828f/artifacts/cam_labels
visualization_mode: "1"
max_concurrent: 1
nuclei_path: ${output_path}
mlflow_artifact_path: nuclei_masks

metadata:
  run_name: Nuclei Masks — ${visualization_mode_names.${visualization_mode}}
  hyperparams:
    mask_tile_width: ${mask_tile_width}
    mask_tile_height: ${mask_tile_height}
    pred_thr: ${oc.select:pred_thr, null}
