# @package _global_

mlflow:
  tracking_uri: http://mlflow.rationai-mlflow:5000/

train_data_path: /mnt/data/MOU/prostate/tile_level_annotations
test_data_path: /mnt/data/MOU/prostate/tile_level_annotations_test

reporter:
  title: Nuclei Segmentation Masks
  template_asset_path: report_template.html
  metrics_run_ids: []

  save:
    _target_: report.save.MLFlowReportStorer
    artifact_path: report.html
    metadata:
      user: xrusnack
      experiment_name: Nuclei Graph — Transformer
      run_name: Report
      description: ""

  background:
    _target_: report.masks.ParquetSlideDatasetMLFlowMaskRetriever
    artifact_uris:
      #- mlflow-artifacts:/72/975fc886053045cea1496b7d49c5da28/artifacts/Prostate Nuclei Graph Dataset - test
      - mlflow-artifacts:/72/975fc886053045cea1496b7d49c5da28/artifacts/Prostate Nuclei Graph Dataset - train
      #- mlflow-artifacts:/72/975fc886053045cea1496b7d49c5da28/artifacts/Prostate Nuclei Graph Dataset - val
    item_name_col: id
    background_masks_directory: ${train_data_path}
    ground_truth_col: null
    item_extension: .mrxs
    layer_name: Prostate WSI

  mask_retrievers:
    - _target_: report.masks.RunIDMlflowMaskRetriever
      dir_name: cam_masks
      run_id: 20d6c9cfb28d49ab9799328be24ead99
      layer_name: CAM Mask
      shader_conf:
        type: bipolar-heatmap
        params:
          threshold: 30
          opacity: 0.5

    - _target_: report.masks.RunIDMlflowMaskRetriever
      dir_name: annotation_masks
      run_id: 0f1925cc96554daaa7b9d4926ab169cf
      layer_name: Annotation Mask
      shader_conf:
        opacity: 0.5
        type: edge
        color: "#ffff00"
        visible: 0

    - _target_: report.masks.RunIDMlflowMaskRetriever
      dir_name: nuclei_masks
      run_id: ac605ca1c6c346cd86bb44d4c0834d9f
      layer_name: Nuclei Segmentation Mask
      shader_conf:
        type: heatmap
        color: "#0000FF"
        visible: 0

metadata:
  run_name: Report — Nuclei Masks
  description: ""
