# @package _global_

mlflow:
  tracking_uri: http://mlflow.rationai-mlflow:5000/

train_data_path: /mnt/data/MOU/prostate/tile_level_annotations
test_data_path: /mnt/data/MOU/prostate/tile_level_annotations_test

reporter:
  title: Nuclei Segmentation Masks
  template_asset_path: report_template.html
  metrics_run_ids: []

  save:
    _target_: report.save.MLFlowReportStorer
    artifact_path: report.html
    metadata:
      user: xrusnack
      experiment_name: Nuclei Graph — Transformer
      run_name: Report
      description: ""

  background:
    _target_: report.masks.BasicImageRetriever
    source_dir: ${train_data_path}
    globs: ["*.mrxs"]
    layer_name: Prostate WSI

  mask_retrievers:
    - _target_: report.masks.RunIDMlflowMaskRetriever
      dir_name: cam_masks
      run_id: 5ce428634d6c4ec095c9259bdef87eca
      layer_name: CAM Mask
      shader_conf:
        type: bipolar-heatmap
        params:
          threshold: 30
          opacity: 0.6
          colorHigh: "#00ff00" # green
          colorLow: "#ff0000" # red

    - _target_: report.masks.RunIDMlflowMaskRetriever
      dir_name: annotation_masks
      run_id: dab2028a50e7431ba0e93f617b5242b6
      layer_name: Annotation Mask
      shader_conf:
        opacity: 0.5
        type: edge
        color: "#ffff00"
        visible: 0

    - _target_: report.masks.RunIDMlflowMaskRetriever
      dir_name: nuclei_masks
      run_id: 3d2ae17022ec457a9e585c5f86542b5a
      layer_name: Nuclei Segmentation Mask
      shader_conf:
        type: heatmap
        color: "#0000FF"
        visible: 0

metadata:
  run_name: Report — Nuclei Masks
  description: ""
