# @package _global_

_target_: nuclei_graph.callbacks.shape_features_permutation_importances.ShapePermutationImportanceCallback
mlflow_run_id: ${mlflow_run_id}
efd_order: ${data.dataset.efd_order}
feature_group_size: 2
