defaults:
  - hydra: default
  - logger: mlflow
  - _self_

data_path: /mnt/data/MOU/prostate
project_path: /mnt/projects/nuclei_based_wsi_analysis
mlflow_project: mlflow-artifacts:/97

# tile sizes need to be consistent across masks to display correctly in xOpat; this sets project default
mask_tile_width: 512
mask_tile_height: 512

metadata:
  experiment_name: Nuclei Graph — Transformer
  run_name: ???
  description: ""
  hyperparams: {}
