defaults:
  - base
  - _self_

seed: ${random_seed:}
mode: ???
checkpoint: null
dataset: ???

trainer: {}

data:
  batch_size: ???
  num_workers: 10
  eval_num_workers: 2
  metadata: ???
  dataset: ???
  supervision:
    paths: ???
    eval_strategy: ???

model: {}
