defaults:
  - base
  - /experiment/modeling: vanilla_transformer #predict
  - _self_

seed: ${random_seed:}
mode: ???
checkpoint: ???

trainer: {}

data:
  batch_size: ???
  num_workers: 10
  paths:
    features: ???
  mlflow_uris:
    metadata: ???
    supervision: ???
  dataset: ???

model: {}
