defaults:
  - base
  - _self_
  - /experiment/modeling: vanilla_transformer #predict vanilla_transformer

seed: ${random_seed:}
mode: ???
checkpoint: null

trainer:
  enable_checkpointing: true
  max_epochs: 200
  log_every_n_steps: 5

data:
  batch_size: ???
  num_workers: 10
  mlflow_uris:
    metadata: ???
    supervision: ???
  dataset: ???

model:
  lr: ???
  warmup_epochs: ???
  net: ???
