defaults:
  - default
  - /experiment: # TODO
  - _self_

seed: ${random_seed:}
mode: ???
checkpoint: null

trainer: {}

data:
  batch_size: ???
  num_workers: 10
  crop_size: ???
  stats:
    scale_mean: ???
    scale_std: ???
    dist_median: ???

model: {}
