# @package _global_

_target_: nuclei_graph.modeling.models.Transformer
config:
  efd_order: ???
  node_features: ???
  norm_dim: ???
  dim: ???
  hidden_dim: ???
  num_heads: ???
  num_layers: ???
  num_classes: ???
  drop_path_rate: ???
