# @package _global_

metadata_uri: ???
predictions_uri: ???
supervision_dir: ???
label_column: ???
nuclei_threshold: null
graph_threshold: null

mlflow_artifact_path: slide_nuclei_metrics.json
mlflow_run_id: null
mlflow_parent_run_id: null

metadata:
  run_name: NL Test (MMCI) Evaluation
  hyperparams:
    nuclei_threshold: ${nuclei_threshold}
    graph_threshold: ${graph_threshold}
