# @package _global_

metadata_uri: ???
predictions_uri: ???
supervision_dir: ???
label_column: ???
threshold: ???
mlflow_artifact_path: slide_nuclei_metrics.json
mlflow_run_id: null

metadata:
  run_name: "Evaluation"
  hyperparams:
    threshold: ${threshold}
