# @package _global_

metadata_uri: ???
predictions_uri: ???
supervision_uri: ???
label_column: ???
threshold: ???

checkpoint: ???
checkpoint_url: ???

metadata:
  run_name: "Per Slide Metrics"
  description: "Model: [MLflow training run](${checkpoint_url})"
  hyperparams:
    threshold: ${threshold}
