defaults:
  - background: mlflow_tyler
  - save: mlflow_standalone_run

title: CAM Labeled Nuclei Segmentation Masks

background:
  _target_: report.masks.TylerMLFlowMaskRetriever
  artifact_uris:
    - mlflow-artifacts:/72/975fc886053045cea1496b7d49c5da28/artifacts/Prostate Nuclei Graph Dataset - test
  #- mlflow-artifacts:/72/975fc886053045cea1496b7d49c5da28/artifacts/Prostate Nuclei Graph Dataset - train
  #- mlflow-artifacts:/72/975fc886053045cea1496b7d49c5da28/artifacts/Prostate Nuclei Graph Dataset - val
  item_name_col: id
  background_masks_directory: /mnt/data/Projects/Data/MOU/prostate/tile_level_annotations_test
  ground_truth_col: null
  layer_name: Prostate WSI
  item_extension: .mrxs

mask_retrievers:
  - _target_: report.masks.RunIDMlflowMaskRetriever
    run_id: 8e9d06de7da14e339558caa0fabb6cbf
    dir_name: cam_masks
    layer_name: CAM Mask
    shader_conf:
      type: bipolar-heatmap
      params:
        threshold: 30
        opacity: 0.5
  - _target_: report.masks.RunIDMlflowMaskRetriever
    run_id: 5eac1bd29164449580ace5c1aaf69c87
    dir_name: annotation_masks
    layer_name: Annotation Carcinoma Mask
    shader_conf:
      opacity: 0.5
      type: edge
      color: "#ffff00"
      visible: 0
  - _target_: report.masks.RunIDMlflowMaskRetriever
    run_id: 25d74715bf7447b59d2fc8e992d2fe03
    dir_name: nuclei_masks
    layer_name: CAM Labeled Nuclei Segmentation Mask
    shader_conf:
      type: heatmap
      color: "#0000FF"
      visible: 0

save:
  metadata:
    user: ${user}
    experiment_name: Nuclei Graph — Transformer
    run_name: "Report[test] CAM Nuclei Annotations"
    description: ""
